### ISSUE TITLE
unable to open /proc/sys/kernel/bpf_stats_enabled

### ISSUE THREAD

**Issue by fuwx295** [elastic/otel-profiling-agent#22]
# Describe
When running the profiling agent 
![image](https://github.com/elastic/otel-profiling-agent/assets/88039311/de46f776-5278-447b-94e3-d8c63a405db9)

# How to reproduce ?
The machine kernel version was originally 3.10, but the agent supports a minimum kernel version of 4.19, so the machine kernel was upgraded
<img width="936" alt="image" src="https://github.com/elastic/otel-profiling-agent/assets/88039311/a17de11f-6196-4a6f-b0c2-c16bdb8ca2f9">

However, I found that there is no `/proc/sys/kernel/bpf_status_enabled` after the upgrade
![image](https://github.com/elastic/otel-profiling-agent/assets/88039311/5fd9bc01-1a93-4372-84ae-a7780f44fed9)

This kernel parameter is only available in the 5.1 kernel
![image](https://github.com/elastic/otel-profiling-agent/assets/88039311/6153c13c-b58c-492f-b2bf-4028f45c6adb)
# What did you expect to see?
I want to run the agent successfully on a kernel 4.19 machine

# Environment (please complete the following information)
![image](https://github.com/elastic/otel-profiling-agent/assets/88039311/53dc1546-bccb-4ded-b6f9-161c7e622759)

**Comment by rockdaboot** [comment]
The error message about bpf_stats_enabled is not a fatal one.
The real reason why the agent stopped or didn't work is that there was no endpoint for receiving the data ("failed to setup gRPC connection"). Please run devfiler as documented and try again.

**Comment by fuwx295** [comment]
> The error message about bpf_stats_enabled is not a fatal one. The real reason why the agent stopped or didn't work is that there was no endpoint for receiving the data ("failed to setup gRPC connection"). Please run devfiler as documented and try again.

Received, thanks! Everything is back to normal now. Thanks for your help!
