### ISSUE TITLE
Can this agent be used for nginx ?

### ISSUE THREAD

**Issue by Minam0** [elastic/otel-profiling-agent#23]
Can this agent be used for nginx ?

**Comment by rockdaboot** [comment]
The agent is a full system CPU profiler, profiling all your processes and kernel CPU usage (even async kernel threads). So you can use it for nginx as well :)

**Comment by inge4pres** [comment]
@Minam0 you may need to add out-of-band debug symbols for nginx if it is built without them.
I am unable to find if the default nginx build ships debug symbols.

**Comment by athre0z** [comment]
Closing this as resolved -- please feel free to reopen if there are further questions in this regard.
