### ISSUE TITLE
Devfiler macOS viewer doesn't work due to looking for a dylib in a nix store

### ISSUE THREAD

**Issue by agnosticlines** [elastic/otel-profiling-agent#4]
```
dyld[56719]: Library not loaded: /nix/store/9pqgglls92szg4pksajafi8sq1nxxk28-libiconv-50/lib/libiconv.dylib
  Referenced from: <B9A7E9BE-4340-386B-8D00-13BC83A5CB2F> /Applications/devfiler.app/Contents/MacOS/devfiler
  Reason: tried: '/nix/store/9pqgglls92szg4pksajafi8sq1nxxk28-libiconv-50/lib/libiconv.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/nix/store/9pqgglls92szg4pksajafi8sq1nxxk28-libiconv-50/lib/libiconv.dylib' (no such file), '/nix/store/9pqgglls92szg4pksajafi8sq1nxxk28-libiconv-50/lib/libiconv.dylib' (no such file)
[1]    56719 abort      ./devfiler
```

Seems to be looking for a dylib in a nix store which isn't present on my system

**Comment by athre0z** [comment]
Oops! Yeah, indeed: it looks like I accidentally linked libiconv from Nix store via a global Cargo config that I had forgotten about. Thank you for the detailed report! Could you try again with the new download link from [this PR](https://github.com/elastic/otel-profiling-agent/pull/5) and let me know whether that resolves the issue?

**Comment by athre0z** [comment]
I tested the updated build with a second Mac and it seems to be working now. This is a pretty breaking issue, so I didn't want to wait before merging. If the issue persists, please feel free to reopen!
