### ISSUE TITLE
Does this support Lua and Luajit?

### ISSUE THREAD

**Issue by chengshuyi** [elastic/otel-profiling-agent#40]
I looked at the bpf code in the repository, and it seems that there is no lua/luajit part. Will lua/luajit be supported in the future? Thanks!

**Comment by rockdaboot** [comment]
The future OTEL repository is open to contributions from the community.
Driving lua/luajit support is highly appreciated, and my personal guess is that it will come.

**Comment by brancz** [comment]
FYI we're 95% there in Parca Agent (some customers already testing it), and plan to port it to this.

**Comment by myzhan** [comment]
Happy to see that happen. Programs like [cloudwu/skynet](https://github.com/cloudwu/skynet) have multiple lua vms in one process, is that supported?

**Comment by brancz** [comment]
I don’t know for sure, our primary focus is for openresty workloads.
