### ISSUE TITLE
[bug] failing due to docker type removed in docker/docker dependency

### ISSUE THREAD

**Issue by tsint** [elastic/otel-profiling-agent#47]
As per https://github.com/moby/moby/issues/47980#issuecomment-2168178707, they accidentally released a 27.0.0 tag, they'll release the stable 27 version as 27.0.1.
Please revert back the Go module version to v26.1.4 instead.

**Comment by rockdaboot** [comment]
It looks like 27.0.1 is already there. Can you have a look at #48?
