### ISSUE TITLE
The comparison between Java profiling by otel-profiling-agent and async-profiler, what are the advantages and disadvantages?

### ISSUE THREAD

**Issue by chengshuyi** [elastic/otel-profiling-agent#93]
I'm considering replacing async-profiler with otel-profiling-agent for CPU profiling, do you have any recommendations? Thanks.

**Comment by florianl** [comment]
Hi @chengshuyi  :wave: 
Thanks for your interest in this project.
async-profiler and this project fulfill very different pruposes and therefore provide different information, while some provided information still overlaps.
Async-profiler is a profiler for a very specfic runtime. It can tell you everything this particular runtime can do/see. On the same time, this profiler misses out on the system part.
While on the other hand, otel-profiling-agent is designed as a whole system profiler. Consequently it samples every process, independent of the runtime, provides you information about the kernel stack, but maybe can not provide (yet) the very same details as a runtime profiler, like async-profiler. 
Hope this helps.
