### ISSUE TITLE
Feature: Consider config regex to filter processes, in order to further reduce overhead.

### ISSUE THREAD

**Issue by CherishCai** [elastic/otel-profiling-agent#95]
Currently, the `otel-profiling-agent` performs collect_trace sampling all processes on the machine. Does it mean that in actual use, there are too many other DevOps's processes on the machine that do not require attention, but only focus on some processes (such as java/nginx/go/etc...)

**Comment by CherishCai** [comment]
Sorry, `includeTracers` already has similar abilities.

**Comment by florianl** [comment]
Hi @CherishCai :wave:
Thanks for your interest in this project. otel-profiling-agent is a whole-system profiler. As such this agent does not differentiate between processes or limits the unwinding to predefined processes.
`includeTracers` limits just the unwinding of interpreted processes - e.g. if only `python` is enabled, you will get the interpreted stack for python only. Other processes, that use interpreters, will also be sampled - but their interpreted stack will not be unwound.

**Comment by CherishCai** [comment]
@florianl Thank you for your detailed reply.
Can we assume that it will end prematurely because cannot find the unwinder and instead use `PROG_UNWIND_STOP` ?

relate code: 
- native_stack_trace.ebpf.c
```C
  error = get_next_unwinder_after_native_frame(record, &unwinder);
```
- get_next_unwinder_after_native_frame
```C
// get_next_unwinder_after_native_frame determines the next unwinder program to run
// after a native stack frame has been unwound.
static inline __attribute__((__always_inline__))
ErrorCode get_next_unwinder_after_native_frame(PerCPURecord *record, int *unwinder) {
  UnwindState *state = &record->state;
  *unwinder = PROG_UNWIND_STOP;

  if (state->pc == 0) {
    DEBUG_PRINT("Stopping unwind due to unwind failure (PC == 0)");
    state->error_metric = metricID_UnwindErrZeroPC;
    return ERR_NATIVE_ZERO_PC;
  }

  DEBUG_PRINT("==== Resolve next frame unwinder: frame %d ====", record->trace.stack_len);
  ErrorCode error = resolve_unwind_mapping(record, unwinder);
  if (error) {
    return error;
  }

  if (*unwinder == PROG_UNWIND_NATIVE) {
    *unwinder = get_next_interpreter(record);
  }

  return ERR_OK;
}
```
- resolve_unwind_mapping
```C
  PIDPage key = {};
  key.prefixLen = BIT_WIDTH_PID + BIT_WIDTH_PAGE;
  key.pid = __constant_cpu_to_be32((u32) pid);
  key.page = __constant_cpu_to_be64(pc);

  // Check if we have the data for this virtual address
  PIDPageMappingInfo* val = bpf_map_lookup_elem(&pid_page_to_mapping_info, &key);
  if (!val) {
    DEBUG_PRINT("Failure to look up interval memory mapping for PC 0x%lx",
                (unsigned long) pc);
    state->error_metric = metricID_UnwindNativeErrWrongTextSection;
    return ERR_NATIVE_NO_PID_PAGE_MAPPING;
  }
```

**Comment by florianl** [comment]
The unwinding process will produces frame information until a stop condition is hit - e.g. `PROG_UNWIND_STOP`. E.g. if you limit `includeTracers` to python only, then for perl processes you will get the corresponding native frames and kernel frames, but miss out on the interpreted stack frames of the perl.

**Comment by CherishCai** [comment]
@florianl Thanks again for your reply 💗
